# mp3dcat = [
#     "void",
#     "table"
#  ]
    # "wall",
    # "floor",
    # "chair",
    # "door",
    # "table",
    # "picture",
    # "cabinet",
    # "window",
    # "sofa",
    # "bed",
    # "curtain",
    # "plant",
    # "sink",
    # "stairs",
    # "ceiling",
    # "toilet",
    # "stool",
    # "towel",
    # "mirror",
    # "tv_monitor",
    # "shower",
    # "column",
    # "bathtub",
    # "fireplace",
    # "lighting",
    # "beam",
    # "railing",
    # "shelving",
    # "blinds",
    # "gym_equipment",
    # "appliances",
    # "clothes",
#    "furniture",
#    "objects",
#    "seating",
#    "chest_of_drawers",
#    "board_panel",
#    "cushion",
#    "counter",


mp3dcat = [
    "void",
    "wall",
    "floor",
    "chair",
    "door",
    "table",
    "picture",
    "cabinet",
    "cushion",
    "window",
    "sofa",
    "bed",
    "curtain",
    "chest_of_drawers",
    "plant",
    "sink",
    "stairs",
    "ceiling",
    "toilet",
    "stool",
    "towel",
    "mirror",
    "tv_monitor",
    "shower",
    "column",
    "bathtub",
    "counter",
    "fireplace",
    "lighting",
    "beam",
    "railing",
    "shelving",
    "blinds",
    "gym_equipment",
    "seating",
    "board_panel",
    "furniture",
    "appliances",
    "clothes",
    "objects",
    ]
